feat: python script
drewdavis418/java-autograder pull request #1
Opened 2022-04-16 23:09 UTC by Hydrophobefireman

wip.. needs testing

2022-04-17 01:35 UTC, drewdavis418 commented
Thanks! I'll reach out to you on how to test it.

2022-04-17 22:03 UTC, jacob-zietek submitted a review, later dismissed
Looks good to me!

2022-04-17 23:14 UTC, drewdavis418 requested changes
Thanks for submitting this! I have a few suggestions and requests before merging.

2022-04-17 23:17 UTC, jacob-zietek commented on run_autograder
> +    java_files = filter_files(submission.glob("*.java"))
A list comprehension can be used in lieu of the function filter_files. `[f for f in submission.glob("*.java") if f.is_file()]` This can also be applied to the kotlin files. Also, please use `rglob` instead of `glob` so that the search goes through all folders instead of just the current directory.

2022-04-17 23:19 UTC, drewdavis418 commented on run_autograder
> +    java_files = filter_files(submission.glob("*.java"))
+1

2022-04-17 23:28 UTC, Hydrophobefireman commented on run_autograder
> +def _compile(source_files: List[Path], args: List[str]):
private functions and to hide implementation underscores are used here it's basically to denote that this function is to be called only by a higher level function like `compile_$lang`

2022-04-17 23:31 UTC, Hydrophobefireman commented on run_autograder
> +        check=False,
it's usually recommended to be specific about subprocess.run (i usually get warned about this by pylint too)

2022-04-17 23:32 UTC, Hydrophobefireman commented on run_autograder
> +    results = {"tests": []}
code is formatted using [black](https://github.com/psf/black) which is the de-facto code style formatter for python now

2022-04-18 03:59 UTC, Hydrophobefireman commented on run_autograder
> +        return
i guess so but that won't allow us to combine errors from both compilations. I have inlined it within the _compile anyway  for now

2022-04-18 04:58 UTC, drewdavis418 commented on run_autograder
> +        return
Sure, that's sort of why I suggest just having one function that does the compiling for all the files (or at least let that be the entry point for compiling, rather than asking to compile Java and Kotlin files separately at the call site).

2022-04-18 05:00 UTC, drewdavis418 commented on run_autograder
> +    results = {"tests": []}
Cool, sounds good. In that case, I think a good addition (for later) would be to run `black` on pull requests to show errors and also make it easy to apply fixes from the dev environment.

2022-04-18 05:06 UTC, drewdavis418 commented on run_autograder
> +def _compile(source_files: List[Path], args: List[str]):
Got it. Based on my other comments, I really do think it would be better to make this the "entry point" (as to speak) for compiling source code. So I think it could be renamed to something like:

```suggestion
def compile_source(files: List[Path]):
```

2022-04-18 05:20 UTC, drewdavis418 requested changes

2022-04-18 05:20 UTC, drewdavis418 commented on run_autograder
> +    # pylint: disable=missing-docstring
Hmm I guess I'm a bit confused at this point. You mentioned using `black` for code style enforcement, but here I see `pylint` used.

At any rate, if the choice is between needing to disable a linter rule inline and adding a docstring comment, I definitely prefer the docstring.

2022-04-18 05:20 UTC, drewdavis418 commented on run_autograder
> +    kt_files = [f for f in submission.glob("*.kt") if f.is_file()]
It's ok with me to keep the `find_files` function; sorry if that was at all confusing. I think the function signature could look like

```python
def find_source_files() -> List[Path]:
```

Then you could just pass that list of Paths into the `compile` function, and let it figure out how to split out the files again to compile them properly. Is it less efficient? Yes, probably. But I would like to prioritize readability (and potentially extendability), and I don't think merging two lists just to break them back out again will cost us too much in terms of execution time. I could also get behind a dictionary approach, maybe something like

```python
{
  "java": [java_files_go_here],
  "kotlin": [kotlin_files_go_here],
}
```

Also, still need to use `rglob` here, as @jacob-zietek mentioned, so that we can recurse into the submission directory and get all the source files.

2022-04-18 05:20 UTC, drewdavis418 commented on run_autograder
> +            "output": "No java or kotlin file found in your submission.",
```suggestion
            "output": "Unable to compile submission",
```

2022-04-18 05:20 UTC, drewdavis418 commented on run_autograder
> +    compile_kt(kt_files)
See above comment about merging into one `compile` function.

2022-04-18 05:20 UTC, drewdavis418 commented on run_autograder
> +        return None
Just had another idea. We could move the check for source files from `main` into here. It may even allow you to only have `results_file.write_text` once in the entire file.

2022-04-18 06:41 UTC, Hydrophobefireman commented on run_autograder
> +        return None
the `compile_source` function would be called twice, so we need to catch the no file existing case before we call this function (otherwise it will throw even if only java files exist but kotlin files don't)

2022-04-18 06:42 UTC, Hydrophobefireman commented on run_autograder
> +    # pylint: disable=missing-docstring
pylint+black (black is the formatter and pylint is the linter)

2022-04-18 06:56 UTC, Hydrophobefireman commented on run_autograder
> +    compile_kt(kt_files)
okay i just wrote a single compile function and personally it looks a lot more involved than before. 
Maybe i'm not understanding it right but if I have to handle all the cases and subprocess calls in a single function it's looking a lot more complicated

2022-04-19 02:56 UTC, drewdavis418 commented on run_autograder
> +    compile_kt(kt_files)
Let's talk offline so I can share what I have in mind. Then we can discuss it at higher fidelity and determine what's the best course of action.

2022-04-19 03:04 UTC, drewdavis418 commented on run_autograder
> +        return None
I think we resolved this offline, so I'll close this thread. Feel free to re-open if we need to discuss this further.

2022-04-19 05:00 UTC, drewdavis418 commented on run_autograder
>          sys.exit(1)
This is very elegant. Nice!

2022-04-19 05:16 UTC, drewdavis418 requested changes
This is really starting to come together, and I like what I see! Just a few more things and I think this is good to go

2022-04-19 05:16 UTC, drewdavis418 commented on run_autograder
> +                        "name": "Compiler Output",
Since this is the same as above, I think it could be factored out (e.g., you could just store `tests.output` in the `err_result`). But if you don't want to change it now, we can always update it later.

2022-04-19 05:16 UTC, drewdavis418 commented on run_autograder
> +    return (result.returncode, result.stdout)
Frankly, if there is a zero return code, we don't care about the output, so I think this could be simplified to just return the `result` itself. I think that would be easier to understand at the use site in `compile_files` as well:

```python
java_compilation = _compile_java(source["java"])
if java_compilation.returncode != 0:
  err_result.tests.output = java_compilation.stderr
```

2022-04-19 05:16 UTC, drewdavis418 commented on run_autograder
> +    if not source["java"] and not source["kotlin"]:
I don't think this is logically correct. This should always be true, correct? (since you are returning the dictionary in `find_source_files`)

If this does work as intended, then the check inside of `_compile` is not necessary.

2022-04-19 05:16 UTC, drewdavis418 commented on run_autograder
> +    Compile the java and kotline files, handle any exception,
typo
```suggestion
    Compile the Java and Kotlin files, handle any exception,
```

2022-04-19 05:16 UTC, drewdavis418 commented on run_autograder
> +            errors += f"{java_result.decode()}\n"
Not sure if the newline is needed here, since I think the compiler should emit a final newline after running. Did you test this and find something different? We don't want any spacing between the Java and Kotlin file compiler errors, they should sit right next to each other.

2022-04-19 05:16 UTC, drewdavis418 commented on run_autograder
> +    return (result.returncode, result.stdout)
If we're just returning the `result`, then I don't think we need a `_compile` function anymore; you can just call `run()` with the correct arguments in `_compile_java` and `_compile_kt`.

2022-04-19 05:16 UTC, drewdavis418 commented on run_autograder
> +  04/17/2022
bump me

```suggestion
  04/18/2022
```

2022-04-19 05:28 UTC, Hydrophobefireman commented on run_autograder
> +                        "name": "Compiler Output",
that would break the None case no?

2022-04-19 05:36 UTC, Hydrophobefireman commented on run_autograder
> +            errors += f"{java_result.decode()}\n"
hmm yeah i haven't tested java + kt yet, i'll remove the newlines

2022-04-19 05:36 UTC, Hydrophobefireman commented on run_autograder
> +    if not source["java"] and not source["kotlin"]:
the logic should be fine, i'm checking the dictionary's key (_compile has been removed anyway)

2022-04-21 00:16 UTC, drewdavis418 commented on run_autograder
> +                        "name": "Compiler Output",
I don't think so based on what I had in mind, but we can worry about it later.

2022-04-21 00:48 UTC, drewdavis418 approved these changes
Tested on my machine and works well. Great job!

2022-04-21 00:48 UTC, merged